const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),path=require('path');
function setup(){
  const data={},elements={},c=vm.createContext({console,Date,Math,JSON,Map,Set,Number,String,Array,Object,Promise,URL,Blob,AbortController,setTimeout,clearTimeout,localStorage:{getItem:k=>data[k]??null,setItem:(k,v)=>data[k]=String(v),removeItem:k=>delete data[k]},document:{addEventListener(){},getElementById:id=>elements[id]??={value:'',textContent:''}},navigator:{onLine:true},window:{},alert(){},confirm:()=>true});
  for(const name of ['app.js','quick-check.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,name),'utf8'),c);
  vm.runInContext('renderQuickCheck=renderAll=renderSettings=loadRouteFromLive=()=>{}',c);
  return {c,data,run:s=>vm.runInContext(s,c)};
}
function record(id,start,h,type='drive'){const end=new Date(+new Date(start)+h*3600000).toISOString();return {id,source:'punch',start,end,segments:[{type,start,end}]}}
let count=0;function test(name,fn){fn();console.log('PASS '+name);count++}
test('empty days and missing periods never report compliance',()=>{const x=setup(),m=x.run('quickModel("2026-01-06",new Date("2026-02-01"))');assert.equal(m.level,'pending');assert.equal(m.biweek.level,'pending');assert.ok(m.issues.some(i=>i.code==='missing-day'))});
test('confirmed days off provide coverage and are not punches',()=>{const x=setup();x.run('settings.quickCheck={daysOff:quickDates(new Date("2026-01-05"),new Date("2026-01-19")),exceptions:{}}');const m=x.run('quickModel("2026-01-06",new Date("2026-02-01"))');assert.equal(m.off,true);assert.equal(m.day.length,0);assert.equal(m.biweek.level,'good');assert.equal(x.run('records.length'),0)});
test('open periods remain pending with every day marked off',()=>{const x=setup();x.run('settings.quickCheck={daysOff:quickDates(new Date("2026-01-05"),new Date("2026-01-19")),exceptions:{}}');assert.equal(x.run('quickModel("2026-01-06",new Date("2026-01-10")).biweek.level'),'pending')});
test('48h driving clips segments at window boundaries',()=>{const x=setup();x.c.rows=[record('a','2026-01-05T22:00:00',10),record('b','2026-01-06T22:00:00',10),record('c','2026-01-07T21:00:00',4)];x.run('records=rows');const m=x.run('quickModel("2026-01-06",new Date("2026-02-01"))');assert.equal(m.prevAvg,10.5);assert.equal(m.nextAvg,7);assert.equal(m.twoLevel,'pending')});
test('two day threshold requires both pairs above nine',()=>{const x=setup();x.c.rows=[record('a','2026-01-05T00:00:00',10),record('b','2026-01-06T00:00:00',10),record('c','2026-01-07T00:00:00',10)];x.run('records=rows');assert.equal(x.run('quickModel("2026-01-06",new Date("2026-02-01")).twoLevel'),'bad');x.c.rows=[record('a','2026-01-05T00:00:00',8),record('b','2026-01-06T00:00:00',10),record('c','2026-01-07T00:00:00',10)];x.run('records=rows');assert.equal(x.run('quickModel("2026-01-06",new Date("2026-02-01")).twoLevel'),'good')});
test('24h restraint includes a following shift',()=>{const x=setup();x.c.rows=[record('a','2026-01-05T06:00:00',13,'other'),record('b','2026-01-06T03:00:00',4,'other')];x.run('records=rows');assert.equal(x.run('quickModel("2026-01-05",new Date("2026-02-01")).rolling'),16)});
test('missing previous day produces review even with old shift',()=>{const x=setup();x.c.rows=[record('a','2026-01-02T06:00:00',1),record('b','2026-01-05T06:00:00',1)];x.run('records=rows');assert.ok(x.run('quickModel("2026-01-05").issues.some(i=>i.code==="missing-prev")'))});
test('long distance flag never silently waives normal excess',()=>{const x=setup();x.c.rows=[record('a','2026-01-05T06:00:00',16,'other')];x.run('records=rows;settings.quickCheck={daysOff:[],exceptions:{"2026-01-05":{longDistance:true,unexpected:true}}}');const m=x.run('quickModel("2026-01-05")');assert.equal(m.level,'bad');assert.ok(m.issues.some(i=>i.code==='long-review'));assert.equal(m.duration,16)});
test('quick settings survive backup restore',()=>{const x=setup();x.run('settings.quickCheck={daysOff:["2026-01-05"],exceptions:{"2026-01-06":{longDistance:true,unexpected:false}}};commitBackup(validateBackup({records:[],settings}))');assert.equal(JSON.parse(x.data.truck_kintai_v8_settings).quickCheck.daysOff[0],'2026-01-05');assert.equal(x.run('settings.quickCheck.exceptions["2026-01-06"].longDistance'),true)});
test('malformed quick backup rejected before storage changes',()=>{const x=setup();for(const quickCheck of [{daysOff:['2026-02-30'],exceptions:{}},{daysOff:[],exceptions:{bad:{longDistance:true,unexpected:false}}},{daysOff:[],exceptions:{'2026-01-01':{longDistance:'yes',unexpected:false}}}]){x.c.quickCheck=quickCheck;assert.throws(()=>x.run('validateSettings({...settings,quickCheck})'))}assert.equal(Object.keys(x.data).length,0)});
test('quota failure keeps prior quick preferences',()=>{const x=setup();x.run('settings.quickCheck={daysOff:[],exceptions:{}};localStorage.setItem=()=>{throw Error("quota")};saveQuickPrefs({daysOff:["2026-01-01"],exceptions:{}})');assert.equal(x.run('settings.quickCheck.daysOff.length'),0)});
test('clear all removes holidays and exception flags',()=>{const x=setup();x.run('settings.quickCheck={daysOff:["2026-01-01"],exceptions:{}};clearAll()');assert.equal(x.run('quickPrefs().daysOff.length'),0)});
console.log(count+' quick checks passed');
