const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const source=fs.readFileSync(require('path').join(__dirname,'app.js'),'utf8');
function setup(initial={}){
  const elements={},data={...initial},alerts=[];
  const localStorage={getItem:k=>Object.hasOwn(data,k)?data[k]:null,setItem:(k,v)=>{data[k]=String(v)},removeItem:k=>{delete data[k]}};
  const context=vm.createContext({console,Date,Math,JSON,Map,Set,Number,String,Array,Object,Promise,URL,Blob,AbortController,setTimeout,clearTimeout,localStorage,document:{addEventListener(){},getElementById(id){return elements[id]??={value:'',textContent:'',innerHTML:''}}},window:{},navigator:{onLine:false},alert:x=>alerts.push(x),confirm:()=>true});
  vm.runInContext(source,context);
  vm.runInContext('renderAll=()=>{};renderRest=()=>{};renderSettings=()=>{};loadRouteFromLive=()=>{};acquireGps=()=>new Promise(()=>{});',context);
  return {context,data,alerts,run:s=>vm.runInContext(s,context)};
}
function rec(start,end,type='other',id='r'){return {id,source:'punch',start,end,segments:[{type,start,end}]}}
const results=[];
async function test(name,fn){try{await fn();results.push({name,status:'PASS'});console.log('PASS '+name)}catch(e){results.push({name,status:'FAIL',error:e.stack});console.error('FAIL '+name+' '+e.stack)}}
const pause=()=>new Promise(r=>setTimeout(r,0));
(async()=>{
await test('auto drive and repeated activity tap',()=>{const x=setup();x.run('startShift();startActivity("load");startActivity("load");endActivity("load");endShift()');assert.deepEqual(Array.from(x.run('records[0].segments.map(s=>s.type)')),['drive','load','drive']);assert.equal(x.run('live'),null)});
await test('overnight scheduled work has no overtime',()=>{const x=setup();x.context.r=rec('2026-09-01T22:00:00','2026-09-02T05:00:00');x.run('settings.scheduledStart="22:00";settings.scheduledEnd="05:00"');assert.equal(x.run('payableOtHours(r)'),0);assert.equal(x.run('applyPay([r]).get("r").pay'),2100)});
await test('overnight boundaries and night premium',()=>{const x=setup();x.context.r=rec('2026-09-01T21:00:00','2026-09-02T06:00:00');x.run('settings.scheduledStart="22:00";settings.scheduledEnd="05:00"');const p=x.run('applyPay([r]).get("r")');assert.equal(p.ot,2);assert.equal(p.night,7);assert.equal(p.pay,5100)});
await test('early morning belongs to previous schedule interval',()=>{const x=setup();x.context.r=rec('2026-09-02T00:00:00','2026-09-02T05:00:00');x.run('settings.scheduledStart="22:00";settings.scheduledEnd="05:00"');assert.equal(x.run('scheduledOutsideHours(r)'),0)});
await test('two shifts daily overtime and required break',()=>{const x=setup();x.context.rs=[rec('2026-09-01T08:00:00','2026-09-01T13:00:00','other','a'),rec('2026-09-01T13:00:00','2026-09-01T18:00:00','other','b')];x.run('records=rs');const d=x.run('aggregateForMonth("2026-09").daily.get("2026-09-01")');assert.equal(d.ot,2);assert.equal(d.breakShort,1);assert.equal(d.pay,3000);assert.equal(d.records[0].breakShort,1)});
await test('daily break totals are not double counted',()=>{const x=setup();x.context.rs=[rec('2026-09-01T08:00:00','2026-09-01T13:00:00','other','a'),rec('2026-09-01T13:00:00','2026-09-01T19:00:00','other','b')];x.context.rs[1].segments=[{type:'break',start:'2026-09-01T13:00:00',end:'2026-09-01T14:00:00'},{type:'other',start:'2026-09-01T14:00:00',end:'2026-09-01T19:00:00'}];x.run('records=rs');assert.equal(x.run('aggregateForMonth("2026-09").daily.get("2026-09-01").breakShort'),0)});
await test('independent days receive independent standard hours',()=>{const x=setup();x.context.rs=[rec('2026-09-01T08:00:00','2026-09-01T13:00:00','other','a'),rec('2026-09-02T08:00:00','2026-09-02T13:00:00','other','b')];assert.equal(x.run('[...applyPay(rs).values()].reduce((n,p)=>n+p.ot,0)'),0)});
await test('month boundary retains documented start date attribution',()=>{const x=setup();x.context.r=rec('2026-08-31T22:00:00','2026-09-01T05:00:00');x.run('settings.scheduledStart="22:00";settings.scheduledEnd="05:00";records=[r]');assert.equal(x.run('aggregateForMonth("2026-08").daily.get("2026-08-31").work'),7);assert.equal(x.run('aggregateForMonth("2026-09").daily.size'),0)});
await test('monthly sixty hour boundary premium',()=>{const x=setup();x.context.rs=[];for(let i=1;i<=31;i++)x.context.rs.push(rec('2026-08-'+String(i).padStart(2,'0')+'T17:00:00','2026-08-'+String(i).padStart(2,'0')+'T19:00:00','other','r'+i));const p=x.run('applyPay(rs).get("r31")');assert.equal(p.pay,3600)});
await test('rest closes exactly at shift start',()=>{const x=setup();x.run('startRest();startShift()');assert.equal(x.run('restState'),null);assert.equal(x.run('restLog[0].end===live.start'),true)});
await test('GPS result survives shift end',async()=>{const x=setup(),done=[];x.context.capture=()=>new Promise(r=>done.push(r));x.run('acquireGps=capture;startShift();endShift()');done[0]({status:'ok',lat:35,lon:139});done[1]({status:'ok',lat:35,lon:139});await pause();assert.equal(x.run('records[0].startGps.status'),'ok');assert.equal(x.run('records[0].endGps.status'),'ok')});
await test('latest GPS retry wins',async()=>{const x=setup(),done=[];x.context.capture=()=>new Promise(r=>done.push(r));x.run('acquireGps=capture;startShift();setStartGpsForLive()');done[1]({status:'ok',lat:36,lon:139});await pause();done[0]({status:'ok',lat:35,lon:139});await pause();assert.equal(x.run('live.startGps.lat'),36)});
await test('stale GPS callback cannot change restored backup',async()=>{const x=setup(),done=[];x.context.capture=()=>new Promise(r=>done.push(r));x.run('acquireGps=capture;startShift();commitBackup(validateBackup({records:[]}))');done[0]({status:'ok',lat:35,lon:139});await pause();assert.equal(x.run('live'),null);assert.equal(x.run('records.length'),0)});
await test('interrupted GPS becomes retryable after reload',()=>{const x=setup();x.run('startShift();recoverPendingGps()');assert.equal(x.run('live.startGps.status'),'error')});
await test('city data retries and shares in flight request',async()=>{const x=setup();let calls=0;x.context.fetch=async()=>{calls++;if(calls===1)throw Error('offline');return {ok:true,json:async()=>[{pref:'東京都',city:'千代田区',cid:'13101'}]}};await x.run('getLocalGov()');const a=x.run('getLocalGov()'),b=x.run('getLocalGov()');assert.equal((await a).length,1);await b;assert.equal(calls,2);await x.run('getLocalGov()');assert.equal(calls,2)});
await test('cached city data works without a network request',async()=>{const x=setup({truck_kintai_v8_localgov_cache:JSON.stringify([{pref:'東京都',city:'千代田区',cid:'13101'}])});x.context.fetch=()=>{throw Error('must not fetch')};assert.equal((await x.run('getLocalGov()')).length,1)});
await test('invalid restore preserves all saved data',()=>{const x=setup();x.context.r=rec('2026-09-01T08:00:00','2026-09-01T09:00:00');x.run('records=[r];saveAll()');const before=JSON.stringify(x.data);x.context.FileReader=class{readAsText(){this.result='{"records":[null]}';this.onload()}};x.run('restoreFile({})');assert.equal(JSON.stringify(x.data),before);assert.equal(x.run('records[0].id'),'r');assert.match(x.alerts[0],/復元できません/)});
await test('malicious and duplicate IDs rejected',()=>{const x=setup();x.context.r=rec('2026-09-01T08:00:00','2026-09-01T09:00:00','other',"x');alert(1);//");assert.throws(()=>x.run('validateBackup({records:[r]})'));x.context.r.id='same';assert.throws(()=>x.run('validateBackup({records:[r,r]})'))});
await test('bad timestamp, reversed and overlapping segments rejected',()=>{const x=setup();x.context.r=rec('2026-02-30T08:00:00','2026-03-02T09:00:00');assert.throws(()=>x.run('validateBackup({records:[r]})'));x.context.r=rec('2026-09-01T09:00:00','2026-09-01T08:00:00');assert.throws(()=>x.run('validateBackup({records:[r]})'));x.context.r=rec('2026-09-01T08:00:00','2026-09-01T09:00:00');x.context.r.segments.push({...x.context.r.segments[0]});assert.throws(()=>x.run('validateBackup({records:[r]})'))});
await test('bad settings and active type rejected',()=>{const x=setup();assert.throws(()=>x.run('validateBackup({records:[],settings:{hourlyRate:-1}})'));assert.throws(()=>x.run('validateBackup({records:[],settings:[]})'));x.run('startShift()');assert.throws(()=>x.run('validateBackup({records:[],live:{...live,active:{type:"evil",start:live.start}}})'))});
await test('valid v8.5 backup roundtrip',()=>{const x=setup();x.context.r=rec('2026-09-01T08:00:00','2026-09-01T09:00:00');x.run('commitBackup(validateBackup({app:"truck-kintai-v8",version:"8.5.0",records:[r],settings,restLog:[]}))');assert.equal(x.run('records[0].id'),'r');assert.equal(x.run('settings.hourlyRate'),1200);assert.equal(x.data.truck_kintai_v8_restore_journal,undefined)});
await test('storage failure rolls all keys back',()=>{const x=setup();x.context.r=rec('2026-09-01T08:00:00','2026-09-01T09:00:00');x.run('records=[r];saveAll()');const before=JSON.stringify(x.data),set=x.context.localStorage.setItem;let count=0;x.context.localStorage.setItem=(k,v)=>{if(++count===3)throw Error('quota');set(k,v)};assert.throws(()=>x.run('commitBackup(validateBackup({records:[]}))'));assert.equal(JSON.stringify(x.data),before);assert.equal(x.run('records[0].id'),'r')});
await test('interrupted restore journal recovers on next load',()=>{const x=setup();x.run('saveAll()');const previous={};for(const key of Object.keys(x.data))previous[key]=x.data[key];const after={...x.data,truck_kintai_v8_records:'[null]',truck_kintai_v8_restore_journal:JSON.stringify(previous)};const recovered=setup(after);assert.equal(recovered.run('records.length'),0);assert.equal(recovered.data.truck_kintai_v8_restore_journal,undefined)});
function timeline(parts){let cursor=new Date('2026-09-01T08:00:00');return parts.map(([type,minutes])=>{const start=cursor.toISOString();cursor=new Date(+cursor+minutes*60000);return {type,start,end:cursor.toISOString()}})}
await test('30 minute break resets four-hour drive',()=>{const x=setup();x.context.r={segments:timeline([['drive',240],['break',30],['drive',240]])};const c=x.run('calcContinuous(r)');assert.equal(c.maxContinuous,4);assert.equal(c.resets,1);assert.equal(c.nonBreakInterruption,false)});
await test('work interruption is flagged for review',()=>{const x=setup();x.context.r={segments:timeline([['drive',120],['load',30],['drive',120]])};assert.equal(x.run('calcContinuous(r).nonBreakInterruption'),true);assert.match(x.run('continuousText(calcContinuous(r))'),/要確認/);assert.equal(x.run('levelForRecord({...calcContinuous(r),rolling24:4.5,restAfter:null,breakShort:0,duration:4.5})'),'warn')});
await test('three short interruptions across driving are violation',()=>{const x=setup();x.context.r={segments:timeline([['drive',30],['break',9],['drive',30],['break',9],['drive',30],['break',9],['drive',30]])};assert.equal(x.run('calcContinuous(r).shortViolation'),true);assert.equal(x.run('levelForRecord({...calcContinuous(r),rolling24:3,restAfter:null,breakShort:0,duration:3})'),'bad')});
await test('a normal interruption clears short sequence',()=>{const x=setup();x.context.r={segments:timeline([['drive',30],['break',9],['drive',30],['break',10],['drive',30],['break',9]])};assert.equal(x.run('calcContinuous(r).shortViolation'),false)});
await test('adjacent breaks merge before counting',()=>{const x=setup();x.context.r={segments:timeline([['drive',240],['break',5],['break',25],['drive',240]])};const c=x.run('calcContinuous(r)');assert.equal(c.shortCount,0);assert.equal(c.maxContinuous,4)});
await test('network JSON request has a timeout',async()=>{const x=setup();x.context.fetch=(url,options)=>new Promise((_,reject)=>options.signal.addEventListener('abort',()=>reject(Error('aborted'))));await assert.rejects(x.run('fetchJson("https://example.invalid",10)'))});
await test('v8.1 settings and empty records override stale legacy data',()=>{const x=setup({truck_kintai_v8_records:'[]',truck_kintai_v8_live:'null',truck_kintai_v8_settings:JSON.stringify({hourlyRate:1800,scheduledStart:'22:00',scheduledEnd:'05:00',dailyStandardHours:8,biweekStart:'2026-01-05'}),truck_kintai_v6_settings:'{"hourlyRate":900}',truck_kintai_v6_records:JSON.stringify([rec('2026-08-01T08:00:00','2026-08-01T09:00:00')]),truck_kintai_v8_migrated_802:'1'});x.run('migrateLegacy()');assert.equal(x.run('settings.hourlyRate'),1800);assert.equal(x.run('records.length'),0)});
await test('v7 data migration remains available',()=>{const x=setup({truck_kintai_v7_records:JSON.stringify([rec('2026-08-01T08:00:00','2026-08-01T09:00:00')]),truck_kintai_v7_settings:'{"hourlyRate":1600}'});x.run('migrateLegacy()');assert.equal(x.run('records.length'),1);assert.equal(x.run('settings.hourlyRate'),1600)});
await test('v8.1 per-activity GPS survives backup restore',()=>{const x=setup();x.context.r=rec('2026-08-01T08:00:00','2026-08-01T09:00:00');x.context.r.segments[0].id='segment1';x.context.r.segments[0].startGps={status:'ok',lat:35,lon:139,accuracy:20};x.run('commitBackup(validateBackup({records:[r]}))');assert.equal(x.run('records[0].segments[0].startGps.lat'),35)});
await test('clear prevents v7 data from returning',()=>{const x=setup({truck_kintai_v7_records:JSON.stringify([rec('2026-08-01T08:00:00','2026-08-01T09:00:00')])});x.run('clearAll();migrateLegacy()');assert.equal(x.run('records.length'),0)});
fs.writeFileSync(require('path').join(__dirname,'regression-results.json'),JSON.stringify(results,null,2));
console.log(results.filter(r=>r.status==='PASS').length+'/'+results.length+' passed');
if(results.some(r=>r.status==='FAIL'))process.exitCode=1;
})();

